### ISSUE TITLE
Registration code is incorrect

### ISSUE THREAD

**Issue by ericnation** [selaias/meteor-accounts-entry#1]
When I try to Create an Account I get an error alert every time saying Registration Code is Incorrect. Terminal error says -  Exception while invoking method 'entryValidateSignupCode' ReferenceError: Match is not defined at [object Object].Meteor.methods.entryValidateSignupCode (packages/selaias_accounts-entry/server/entry.js:48:1)

METEOR@1.2.0.2
iron:router@1.0.12

Any help would be much appreciated.

**Comment by selaias** [comment]
I think you are missing the check package
can you add it?

**Comment by selaias** [comment]
Did it solved your issue?
Ive added dependency to check package anyway.

**Comment by ericnation** [comment]
Sorry it took so long for me to respond. I thought I would have gotten an email notification when you responded to me.... I'll add that package and let you know! Thanks

**Comment by ericnation** [comment]
That worked! Thank you

**Comment by selaias** [comment]
to receive notifications you need to watch the repo
