### ISSUE TITLE
Translations integration

### ISSUE THREAD

**Issue by talbenbasat** [selaias/meteor-accounts-entry#4]
First of all - Great work,

Second how can I make it work with translations.
Int the 1.1 I've manged to translate using softwarerero:accounts-t9n

This time it doesn't work

Tal

**Comment by selaias** [comment]
Hey the credit should go to the initial owners of this package :)

you can change the default language by typing `i18n.setLanguage('fr');` in client startup.
default language is set to "en", list of available languages at https://github.com/selaias/meteor-accounts-entry/tree/master/shared/i18n
